package pvmi

const (
	// proc_interrupts:
	PROC_INTERRUPTS_TOTAL_METRIC_NAME       = "proc_interrupts_total"
	PROC_INTERRUPTS_INFO_METRIC_NAME        = "proc_interrupts_info"
	PROC_INTERRUPTS_IRQ_LABEL_NAME          = "interrupt"
	PROC_INTERRUPTS_TOTAL_CPU_LABEL_NAME    = "cpu"
	PROC_INTERRUPTS_INFO_DEVICES_LABEL_NAME = "devices"
	PROC_INTERRUPTS_INFO_INFO_LABEL_NAME    = "info"

	// proc_softirqs:
	PROC_SOFTIRQS_TOTAL_METRIC_NAME              = "proc_softirqs_total"
	PROC_SOFTIRQS_TOTAL_IRQ_LABEL_NAME           = "interrupt"
	PROC_SOFTIRQS_TOTAL_IRQ_LABEL_VALUE_HI       = "hi"
	PROC_SOFTIRQS_TOTAL_IRQ_LABEL_VALUE_TIMER    = "timer"
	PROC_SOFTIRQS_TOTAL_IRQ_LABEL_VALUE_NET_TX   = "net_tx"
	PROC_SOFTIRQS_TOTAL_IRQ_LABEL_VALUE_NET_RX   = "net_rx"
	PROC_SOFTIRQS_TOTAL_IRQ_LABEL_VALUE_BLOCK    = "block"
	PROC_SOFTIRQS_TOTAL_IRQ_LABEL_VALUE_IRQ_POLL = "irq_poll"
	PROC_SOFTIRQS_TOTAL_IRQ_LABEL_VALUE_TASKLET  = "tasklet"
	PROC_SOFTIRQS_TOTAL_IRQ_LABEL_VALUE_SCHED    = "sched"
	PROC_SOFTIRQS_TOTAL_IRQ_LABEL_VALUE_HR_TIMER = "hr_timer"
	PROC_SOFTIRQS_TOTAL_IRQ_LABEL_VALUE_RCU      = "rcu"
	PROC_SOFTIRQS_TOTAL_CPU_LABEL_NAME           = "cpu"
)
